apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
metadata:
  name: registry-creds
  namespace: blog
stringData:
  .dockerconfigjson:
    sops_docker_registry:
      server: registry.login.server
      username: registry.login.username
      password: registry.login.password
      email: registry.login.email
