// WARNING: generated by kopium - manual changes will be overwritten
// kopium command: kopium databases.postgresql.cnpg.io -D Default
// kopium version: 0.22.5

#[allow(unused_imports)]
mod prelude {
    pub use kube::CustomResource;
    pub use serde::{Serialize, Deserialize};
}
use self::prelude::*;

#[derive(CustomResource, Serialize, Deserialize, Clone, Debug, Default)]
#[kube(group = "postgresql.cnpg.io", version = "v1", kind = "Database", plural = "databases")]
#[kube(namespaced)]
#[kube(status = "DatabaseStatus")]
#[kube(schema = "disabled")]
#[kube(derive="Default")]
pub struct DatabaseSpec {
    #[serde(default, skip_serializing_if = "Option::is_none", rename = "allowConnections")]
    pub allow_connections: Option<bool>,
    #[serde(default, skip_serializing_if = "Option::is_none", rename = "builtinLocale")]
    pub builtin_locale: Option<String>,
    pub cluster: DatabaseCluster,
    #[serde(default, skip_serializing_if = "Option::is_none", rename = "collationVersion")]
    pub collation_version: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none", rename = "connectionLimit")]
    pub connection_limit: Option<i64>,
    #[serde(default, skip_serializing_if = "Option::is_none", rename = "databaseReclaimPolicy")]
    pub database_reclaim_policy: Option<DatabaseDatabaseReclaimPolicy>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub encoding: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub ensure: Option<DatabaseEnsure>,
    #[serde(default, skip_serializing_if = "Option::is_none", rename = "icuLocale")]
    pub icu_locale: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none", rename = "icuRules")]
    pub icu_rules: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none", rename = "isTemplate")]
    pub is_template: Option<bool>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub locale: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none", rename = "localeCType")]
    pub locale_c_type: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none", rename = "localeCollate")]
    pub locale_collate: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none", rename = "localeProvider")]
    pub locale_provider: Option<String>,
    pub name: String,
    pub owner: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub tablespace: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub template: Option<String>,
}

#[derive(Serialize, Deserialize, Clone, Debug, Default)]
pub struct DatabaseCluster {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub enum DatabaseDatabaseReclaimPolicy {
    #[serde(rename = "delete")]
    Delete,
    #[serde(rename = "retain")]
    Retain,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub enum DatabaseEnsure {
    #[serde(rename = "present")]
    Present,
    #[serde(rename = "absent")]
    Absent,
}

#[derive(Serialize, Deserialize, Clone, Debug, Default)]
pub struct DatabaseStatus {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub applied: Option<bool>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none", rename = "observedGeneration")]
    pub observed_generation: Option<i64>,
}

