// WARNING: generated by kopium - manual changes will be overwritten
// kopium command: kopium imagecatalogs.postgresql.cnpg.io -D Default
// kopium version: 0.22.5

#[allow(unused_imports)]
mod prelude {
    pub use kube::CustomResource;
    pub use serde::{Serialize, Deserialize};
}
use self::prelude::*;

#[derive(CustomResource, Serialize, Deserialize, Clone, Debug, Default)]
#[kube(group = "postgresql.cnpg.io", version = "v1", kind = "ImageCatalog", plural = "imagecatalogs")]
#[kube(namespaced)]
#[kube(schema = "disabled")]
#[kube(derive="Default")]
pub struct ImageCatalogSpec {
    pub images: Vec<ImageCatalogImages>,
}

#[derive(Serialize, Deserialize, Clone, Debug, Default)]
pub struct ImageCatalogImages {
    pub image: String,
    pub major: i64,
}

