// WARNING: generated by kopium - manual changes will be overwritten
// kopium command: kopium objectstores.barmancloud.cnpg.io -D Default
// kopium version: 0.22.5

#[allow(unused_imports)]
mod prelude {
    pub use kube::CustomResource;
    pub use serde::{Serialize, Deserialize};
    pub use std::collections::BTreeMap;
    pub use k8s_openapi::apimachinery::pkg::util::intstr::IntOrString;
}
use self::prelude::*;

#[derive(CustomResource, Serialize, Deserialize, Clone, Debug, Default)]
#[kube(group = "barmancloud.cnpg.io", version = "v1", kind = "ObjectStore", plural = "objectstores")]
#[kube(namespaced)]
#[kube(status = "ObjectStoreStatus")]
#[kube(schema = "disabled")]
#[kube(derive="Default")]
pub struct ObjectStoreSpec {
    pub configuration: ObjectStoreConfiguration,
    #[serde(default, skip_serializing_if = "Option::is_none", rename = "instanceSidecarConfiguration")]
    pub instance_sidecar_configuration: Option<ObjectStoreInstanceSidecarConfiguration>,
    #[serde(default, skip_serializing_if = "Option::is_none", rename = "retentionPolicy")]
    pub retention_policy: Option<String>,
}

#[derive(Serialize, Deserialize, Clone, Debug, Default)]
pub struct ObjectStoreConfiguration {
    #[serde(default, skip_serializing_if = "Option::is_none", rename = "azureCredentials")]
    pub azure_credentials: Option<ObjectStoreConfigurationAzureCredentials>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub data: Option<ObjectStoreConfigurationData>,
    #[serde(rename = "destinationPath")]
    pub destination_path: String,
    #[serde(default, skip_serializing_if = "Option::is_none", rename = "endpointCA")]
    pub endpoint_ca: Option<ObjectStoreConfigurationEndpointCa>,
    #[serde(default, skip_serializing_if = "Option::is_none", rename = "endpointURL")]
    pub endpoint_url: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none", rename = "googleCredentials")]
    pub google_credentials: Option<ObjectStoreConfigurationGoogleCredentials>,
    #[serde(default, skip_serializing_if = "Option::is_none", rename = "historyTags")]
    pub history_tags: Option<BTreeMap<String, String>>,
    #[serde(default, skip_serializing_if = "Option::is_none", rename = "s3Credentials")]
    pub s3_credentials: Option<ObjectStoreConfigurationS3Credentials>,
    #[serde(default, skip_serializing_if = "Option::is_none", rename = "serverName")]
    pub server_name: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub tags: Option<BTreeMap<String, String>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub wal: Option<ObjectStoreConfigurationWal>,
}

#[derive(Serialize, Deserialize, Clone, Debug, Default)]
pub struct ObjectStoreConfigurationAzureCredentials {
    #[serde(default, skip_serializing_if = "Option::is_none", rename = "connectionString")]
    pub connection_string: Option<ObjectStoreConfigurationAzureCredentialsConnectionString>,
    #[serde(default, skip_serializing_if = "Option::is_none", rename = "inheritFromAzureAD")]
    pub inherit_from_azure_ad: Option<bool>,
    #[serde(default, skip_serializing_if = "Option::is_none", rename = "storageAccount")]
    pub storage_account: Option<ObjectStoreConfigurationAzureCredentialsStorageAccount>,
    #[serde(default, skip_serializing_if = "Option::is_none", rename = "storageKey")]
    pub storage_key: Option<ObjectStoreConfigurationAzureCredentialsStorageKey>,
    #[serde(default, skip_serializing_if = "Option::is_none", rename = "storageSasToken")]
    pub storage_sas_token: Option<ObjectStoreConfigurationAzureCredentialsStorageSasToken>,
}

#[derive(Serialize, Deserialize, Clone, Debug, Default)]
pub struct ObjectStoreConfigurationAzureCredentialsConnectionString {
    pub key: String,
    pub name: String,
}

#[derive(Serialize, Deserialize, Clone, Debug, Default)]
pub struct ObjectStoreConfigurationAzureCredentialsStorageAccount {
    pub key: String,
    pub name: String,
}

#[derive(Serialize, Deserialize, Clone, Debug, Default)]
pub struct ObjectStoreConfigurationAzureCredentialsStorageKey {
    pub key: String,
    pub name: String,
}

#[derive(Serialize, Deserialize, Clone, Debug, Default)]
pub struct ObjectStoreConfigurationAzureCredentialsStorageSasToken {
    pub key: String,
    pub name: String,
}

#[derive(Serialize, Deserialize, Clone, Debug, Default)]
pub struct ObjectStoreConfigurationData {
    #[serde(default, skip_serializing_if = "Option::is_none", rename = "additionalCommandArgs")]
    pub additional_command_args: Option<Vec<String>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub compression: Option<ObjectStoreConfigurationDataCompression>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub encryption: Option<ObjectStoreConfigurationDataEncryption>,
    #[serde(default, skip_serializing_if = "Option::is_none", rename = "immediateCheckpoint")]
    pub immediate_checkpoint: Option<bool>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub jobs: Option<i32>,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub enum ObjectStoreConfigurationDataCompression {
    #[serde(rename = "bzip2")]
    Bzip2,
    #[serde(rename = "gzip")]
    Gzip,
    #[serde(rename = "snappy")]
    Snappy,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub enum ObjectStoreConfigurationDataEncryption {
    #[serde(rename = "AES256")]
    Aes256,
    #[serde(rename = "aws:kms")]
    AwsKms,
}

#[derive(Serialize, Deserialize, Clone, Debug, Default)]
pub struct ObjectStoreConfigurationEndpointCa {
    pub key: String,
    pub name: String,
}

#[derive(Serialize, Deserialize, Clone, Debug, Default)]
pub struct ObjectStoreConfigurationGoogleCredentials {
    #[serde(default, skip_serializing_if = "Option::is_none", rename = "applicationCredentials")]
    pub application_credentials: Option<ObjectStoreConfigurationGoogleCredentialsApplicationCredentials>,
    #[serde(default, skip_serializing_if = "Option::is_none", rename = "gkeEnvironment")]
    pub gke_environment: Option<bool>,
}

#[derive(Serialize, Deserialize, Clone, Debug, Default)]
pub struct ObjectStoreConfigurationGoogleCredentialsApplicationCredentials {
    pub key: String,
    pub name: String,
}

#[derive(Serialize, Deserialize, Clone, Debug, Default)]
pub struct ObjectStoreConfigurationS3Credentials {
    #[serde(default, skip_serializing_if = "Option::is_none", rename = "accessKeyId")]
    pub access_key_id: Option<ObjectStoreConfigurationS3CredentialsAccessKeyId>,
    #[serde(default, skip_serializing_if = "Option::is_none", rename = "inheritFromIAMRole")]
    pub inherit_from_iam_role: Option<bool>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub region: Option<ObjectStoreConfigurationS3CredentialsRegion>,
    #[serde(default, skip_serializing_if = "Option::is_none", rename = "secretAccessKey")]
    pub secret_access_key: Option<ObjectStoreConfigurationS3CredentialsSecretAccessKey>,
    #[serde(default, skip_serializing_if = "Option::is_none", rename = "sessionToken")]
    pub session_token: Option<ObjectStoreConfigurationS3CredentialsSessionToken>,
}

#[derive(Serialize, Deserialize, Clone, Debug, Default)]
pub struct ObjectStoreConfigurationS3CredentialsAccessKeyId {
    pub key: String,
    pub name: String,
}

#[derive(Serialize, Deserialize, Clone, Debug, Default)]
pub struct ObjectStoreConfigurationS3CredentialsRegion {
    pub key: String,
    pub name: String,
}

#[derive(Serialize, Deserialize, Clone, Debug, Default)]
pub struct ObjectStoreConfigurationS3CredentialsSecretAccessKey {
    pub key: String,
    pub name: String,
}

#[derive(Serialize, Deserialize, Clone, Debug, Default)]
pub struct ObjectStoreConfigurationS3CredentialsSessionToken {
    pub key: String,
    pub name: String,
}

#[derive(Serialize, Deserialize, Clone, Debug, Default)]
pub struct ObjectStoreConfigurationWal {
    #[serde(default, skip_serializing_if = "Option::is_none", rename = "archiveAdditionalCommandArgs")]
    pub archive_additional_command_args: Option<Vec<String>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub compression: Option<ObjectStoreConfigurationWalCompression>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub encryption: Option<ObjectStoreConfigurationWalEncryption>,
    #[serde(default, skip_serializing_if = "Option::is_none", rename = "maxParallel")]
    pub max_parallel: Option<i64>,
    #[serde(default, skip_serializing_if = "Option::is_none", rename = "restoreAdditionalCommandArgs")]
    pub restore_additional_command_args: Option<Vec<String>>,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub enum ObjectStoreConfigurationWalCompression {
    #[serde(rename = "bzip2")]
    Bzip2,
    #[serde(rename = "gzip")]
    Gzip,
    #[serde(rename = "lz4")]
    Lz4,
    #[serde(rename = "snappy")]
    Snappy,
    #[serde(rename = "xz")]
    Xz,
    #[serde(rename = "zstd")]
    Zstd,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub enum ObjectStoreConfigurationWalEncryption {
    #[serde(rename = "AES256")]
    Aes256,
    #[serde(rename = "aws:kms")]
    AwsKms,
}

#[derive(Serialize, Deserialize, Clone, Debug, Default)]
pub struct ObjectStoreInstanceSidecarConfiguration {
    #[serde(default, skip_serializing_if = "Option::is_none", rename = "additionalContainerArgs")]
    pub additional_container_args: Option<Vec<String>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub env: Option<Vec<ObjectStoreInstanceSidecarConfigurationEnv>>,
    #[serde(default, skip_serializing_if = "Option::is_none", rename = "logLevel")]
    pub log_level: Option<ObjectStoreInstanceSidecarConfigurationLogLevel>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub resources: Option<ObjectStoreInstanceSidecarConfigurationResources>,
    #[serde(default, skip_serializing_if = "Option::is_none", rename = "retentionPolicyIntervalSeconds")]
    pub retention_policy_interval_seconds: Option<i64>,
}

#[derive(Serialize, Deserialize, Clone, Debug, Default)]
pub struct ObjectStoreInstanceSidecarConfigurationEnv {
    pub name: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub value: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none", rename = "valueFrom")]
    pub value_from: Option<ObjectStoreInstanceSidecarConfigurationEnvValueFrom>,
}

#[derive(Serialize, Deserialize, Clone, Debug, Default)]
pub struct ObjectStoreInstanceSidecarConfigurationEnvValueFrom {
    #[serde(default, skip_serializing_if = "Option::is_none", rename = "configMapKeyRef")]
    pub config_map_key_ref: Option<ObjectStoreInstanceSidecarConfigurationEnvValueFromConfigMapKeyRef>,
    #[serde(default, skip_serializing_if = "Option::is_none", rename = "fieldRef")]
    pub field_ref: Option<ObjectStoreInstanceSidecarConfigurationEnvValueFromFieldRef>,
    #[serde(default, skip_serializing_if = "Option::is_none", rename = "fileKeyRef")]
    pub file_key_ref: Option<ObjectStoreInstanceSidecarConfigurationEnvValueFromFileKeyRef>,
    #[serde(default, skip_serializing_if = "Option::is_none", rename = "resourceFieldRef")]
    pub resource_field_ref: Option<ObjectStoreInstanceSidecarConfigurationEnvValueFromResourceFieldRef>,
    #[serde(default, skip_serializing_if = "Option::is_none", rename = "secretKeyRef")]
    pub secret_key_ref: Option<ObjectStoreInstanceSidecarConfigurationEnvValueFromSecretKeyRef>,
}

#[derive(Serialize, Deserialize, Clone, Debug, Default)]
pub struct ObjectStoreInstanceSidecarConfigurationEnvValueFromConfigMapKeyRef {
    pub key: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub optional: Option<bool>,
}

#[derive(Serialize, Deserialize, Clone, Debug, Default)]
pub struct ObjectStoreInstanceSidecarConfigurationEnvValueFromFieldRef {
    #[serde(default, skip_serializing_if = "Option::is_none", rename = "apiVersion")]
    pub api_version: Option<String>,
    #[serde(rename = "fieldPath")]
    pub field_path: String,
}

#[derive(Serialize, Deserialize, Clone, Debug, Default)]
pub struct ObjectStoreInstanceSidecarConfigurationEnvValueFromFileKeyRef {
    pub key: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub optional: Option<bool>,
    pub path: String,
    #[serde(rename = "volumeName")]
    pub volume_name: String,
}

#[derive(Serialize, Deserialize, Clone, Debug, Default)]
pub struct ObjectStoreInstanceSidecarConfigurationEnvValueFromResourceFieldRef {
    #[serde(default, skip_serializing_if = "Option::is_none", rename = "containerName")]
    pub container_name: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub divisor: Option<IntOrString>,
    pub resource: String,
}

#[derive(Serialize, Deserialize, Clone, Debug, Default)]
pub struct ObjectStoreInstanceSidecarConfigurationEnvValueFromSecretKeyRef {
    pub key: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub optional: Option<bool>,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub enum ObjectStoreInstanceSidecarConfigurationLogLevel {
    #[serde(rename = "error")]
    Error,
    #[serde(rename = "warning")]
    Warning,
    #[serde(rename = "info")]
    Info,
    #[serde(rename = "debug")]
    Debug,
    #[serde(rename = "trace")]
    Trace,
}

#[derive(Serialize, Deserialize, Clone, Debug, Default)]
pub struct ObjectStoreInstanceSidecarConfigurationResources {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub claims: Option<Vec<ObjectStoreInstanceSidecarConfigurationResourcesClaims>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub limits: Option<BTreeMap<String, IntOrString>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub requests: Option<BTreeMap<String, IntOrString>>,
}

#[derive(Serialize, Deserialize, Clone, Debug, Default)]
pub struct ObjectStoreInstanceSidecarConfigurationResourcesClaims {
    pub name: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub request: Option<String>,
}

#[derive(Serialize, Deserialize, Clone, Debug, Default)]
pub struct ObjectStoreStatus {
    #[serde(default, skip_serializing_if = "Option::is_none", rename = "serverRecoveryWindow")]
    pub server_recovery_window: Option<BTreeMap<String, ObjectStoreStatusServerRecoveryWindow>>,
}

#[derive(Serialize, Deserialize, Clone, Debug, Default)]
pub struct ObjectStoreStatusServerRecoveryWindow {
    #[serde(default, skip_serializing_if = "Option::is_none", rename = "firstRecoverabilityPoint")]
    pub first_recoverability_point: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none", rename = "lastFailedBackupTime")]
    pub last_failed_backup_time: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none", rename = "lastSuccessfulBackupTime")]
    pub last_successful_backup_time: Option<String>,
}

