// WARNING: generated by kopium - manual changes will be overwritten
// kopium command: kopium scheduledbackups.postgresql.cnpg.io -D Default
// kopium version: 0.22.5

#[allow(unused_imports)]
mod prelude {
    pub use kube::CustomResource;
    pub use serde::{Serialize, Deserialize};
    pub use std::collections::BTreeMap;
}
use self::prelude::*;

#[derive(CustomResource, Serialize, Deserialize, Clone, Debug, Default)]
#[kube(group = "postgresql.cnpg.io", version = "v1", kind = "ScheduledBackup", plural = "scheduledbackups")]
#[kube(namespaced)]
#[kube(status = "ScheduledBackupStatus")]
#[kube(schema = "disabled")]
#[kube(derive="Default")]
pub struct ScheduledBackupSpec {
    #[serde(default, skip_serializing_if = "Option::is_none", rename = "backupOwnerReference")]
    pub backup_owner_reference: Option<ScheduledBackupBackupOwnerReference>,
    pub cluster: ScheduledBackupCluster,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub immediate: Option<bool>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub method: Option<ScheduledBackupMethod>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub online: Option<bool>,
    #[serde(default, skip_serializing_if = "Option::is_none", rename = "onlineConfiguration")]
    pub online_configuration: Option<ScheduledBackupOnlineConfiguration>,
    #[serde(default, skip_serializing_if = "Option::is_none", rename = "pluginConfiguration")]
    pub plugin_configuration: Option<ScheduledBackupPluginConfiguration>,
    pub schedule: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub suspend: Option<bool>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub target: Option<ScheduledBackupTarget>,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub enum ScheduledBackupBackupOwnerReference {
    #[serde(rename = "none")]
    None,
    #[serde(rename = "self")]
    r#_Self,
    #[serde(rename = "cluster")]
    Cluster,
}

#[derive(Serialize, Deserialize, Clone, Debug, Default)]
pub struct ScheduledBackupCluster {
    pub name: String,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub enum ScheduledBackupMethod {
    #[serde(rename = "barmanObjectStore")]
    BarmanObjectStore,
    #[serde(rename = "volumeSnapshot")]
    VolumeSnapshot,
    #[serde(rename = "plugin")]
    Plugin,
}

#[derive(Serialize, Deserialize, Clone, Debug, Default)]
pub struct ScheduledBackupOnlineConfiguration {
    #[serde(default, skip_serializing_if = "Option::is_none", rename = "immediateCheckpoint")]
    pub immediate_checkpoint: Option<bool>,
    #[serde(default, skip_serializing_if = "Option::is_none", rename = "waitForArchive")]
    pub wait_for_archive: Option<bool>,
}

#[derive(Serialize, Deserialize, Clone, Debug, Default)]
pub struct ScheduledBackupPluginConfiguration {
    pub name: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub parameters: Option<BTreeMap<String, String>>,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub enum ScheduledBackupTarget {
    #[serde(rename = "primary")]
    Primary,
    #[serde(rename = "prefer-standby")]
    PreferStandby,
}

#[derive(Serialize, Deserialize, Clone, Debug, Default)]
pub struct ScheduledBackupStatus {
    #[serde(default, skip_serializing_if = "Option::is_none", rename = "lastCheckTime")]
    pub last_check_time: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none", rename = "lastScheduleTime")]
    pub last_schedule_time: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none", rename = "nextScheduleTime")]
    pub next_schedule_time: Option<String>,
}

