import 'blog/justfile'
import 'cert-manager/justfile'
import 'cnpg-database/justfile'
import 'csi-driver-linode/justfile'
import 'metrics-server/justfile'
import 'miniflux/justfile'
import 'wallabag/justfile'
