apiVersion: v1
kind: Secret
metadata:
  name: vikunja-database
  namespace: vikunja
stringData:
  HOST: "main-db-rw.main-db"
  DATABASE: "vikunja"
  USERNAME:
    sops: postgres.app_user.username
  PASSWORD:
    sops: postgres.app_user.password
---
apiVersion: v1
kind: Secret
metadata:
  name: tailscale-auth
  namespace: vikunja
stringData:
  TS_AUTHKEY:
    sops: tailscale.authkey
