apiVersion: v1
kind: Secret
metadata:
  name: umami-postgres
  namespace: umami
stringData:
  username:
    sops: postgres.app_user.username
  password:
    sops: postgres.app_user.password
---
apiVersion: v1
kind: Secret
metadata:
  name: umami-app
  namespace: umami
stringData:
  app_secret:
    sops: umami.app_secret
