// WARNING: generated by kopium - manual changes will be overwritten
// kopium command: kopium schedules.velero.io -D Default
// kopium version: 0.22.5

#[allow(unused_imports)]
mod prelude {
    pub use kube::CustomResource;
    pub use serde::{Serialize, Deserialize};
    pub use std::collections::BTreeMap;
}
use self::prelude::*;

#[derive(CustomResource, Serialize, Deserialize, Clone, Debug, Default)]
#[kube(group = "velero.io", version = "v1", kind = "Schedule", plural = "schedules")]
#[kube(namespaced)]
#[kube(status = "ScheduleStatus")]
#[kube(schema = "disabled")]
#[kube(derive="Default")]
pub struct ScheduleSpec {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub paused: Option<bool>,
    pub schedule: String,
    #[serde(default, skip_serializing_if = "Option::is_none", rename = "skipImmediately")]
    pub skip_immediately: Option<bool>,
    pub template: ScheduleTemplate,
    #[serde(default, skip_serializing_if = "Option::is_none", rename = "useOwnerReferencesInBackup")]
    pub use_owner_references_in_backup: Option<bool>,
}

#[derive(Serialize, Deserialize, Clone, Debug, Default)]
pub struct ScheduleTemplate {
    #[serde(default, skip_serializing_if = "Option::is_none", rename = "csiSnapshotTimeout")]
    pub csi_snapshot_timeout: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub datamover: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none", rename = "defaultVolumesToFsBackup")]
    pub default_volumes_to_fs_backup: Option<bool>,
    #[serde(default, skip_serializing_if = "Option::is_none", rename = "defaultVolumesToRestic")]
    pub default_volumes_to_restic: Option<bool>,
    #[serde(default, skip_serializing_if = "Option::is_none", rename = "excludedClusterScopedResources")]
    pub excluded_cluster_scoped_resources: Option<Vec<String>>,
    #[serde(default, skip_serializing_if = "Option::is_none", rename = "excludedNamespaceScopedResources")]
    pub excluded_namespace_scoped_resources: Option<Vec<String>>,
    #[serde(default, skip_serializing_if = "Option::is_none", rename = "excludedNamespaces")]
    pub excluded_namespaces: Option<Vec<String>>,
    #[serde(default, skip_serializing_if = "Option::is_none", rename = "excludedResources")]
    pub excluded_resources: Option<Vec<String>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub hooks: Option<ScheduleTemplateHooks>,
    #[serde(default, skip_serializing_if = "Option::is_none", rename = "includeClusterResources")]
    pub include_cluster_resources: Option<bool>,
    #[serde(default, skip_serializing_if = "Option::is_none", rename = "includedClusterScopedResources")]
    pub included_cluster_scoped_resources: Option<Vec<String>>,
    #[serde(default, skip_serializing_if = "Option::is_none", rename = "includedNamespaceScopedResources")]
    pub included_namespace_scoped_resources: Option<Vec<String>>,
    #[serde(default, skip_serializing_if = "Option::is_none", rename = "includedNamespaces")]
    pub included_namespaces: Option<Vec<String>>,
    #[serde(default, skip_serializing_if = "Option::is_none", rename = "includedResources")]
    pub included_resources: Option<Vec<String>>,
    #[serde(default, skip_serializing_if = "Option::is_none", rename = "itemOperationTimeout")]
    pub item_operation_timeout: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none", rename = "labelSelector")]
    pub label_selector: Option<ScheduleTemplateLabelSelector>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub metadata: Option<ScheduleTemplateMetadata>,
    #[serde(default, skip_serializing_if = "Option::is_none", rename = "orLabelSelectors")]
    pub or_label_selectors: Option<Vec<ScheduleTemplateOrLabelSelectors>>,
    #[serde(default, skip_serializing_if = "Option::is_none", rename = "orderedResources")]
    pub ordered_resources: Option<BTreeMap<String, String>>,
    #[serde(default, skip_serializing_if = "Option::is_none", rename = "resourcePolicy")]
    pub resource_policy: Option<ScheduleTemplateResourcePolicy>,
    #[serde(default, skip_serializing_if = "Option::is_none", rename = "snapshotMoveData")]
    pub snapshot_move_data: Option<bool>,
    #[serde(default, skip_serializing_if = "Option::is_none", rename = "snapshotVolumes")]
    pub snapshot_volumes: Option<bool>,
    #[serde(default, skip_serializing_if = "Option::is_none", rename = "storageLocation")]
    pub storage_location: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub ttl: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none", rename = "uploaderConfig")]
    pub uploader_config: Option<ScheduleTemplateUploaderConfig>,
    #[serde(default, skip_serializing_if = "Option::is_none", rename = "volumeGroupSnapshotLabelKey")]
    pub volume_group_snapshot_label_key: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none", rename = "volumeSnapshotLocations")]
    pub volume_snapshot_locations: Option<Vec<String>>,
}

#[derive(Serialize, Deserialize, Clone, Debug, Default)]
pub struct ScheduleTemplateHooks {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub resources: Option<Vec<ScheduleTemplateHooksResources>>,
}

#[derive(Serialize, Deserialize, Clone, Debug, Default)]
pub struct ScheduleTemplateHooksResources {
    #[serde(default, skip_serializing_if = "Option::is_none", rename = "excludedNamespaces")]
    pub excluded_namespaces: Option<Vec<String>>,
    #[serde(default, skip_serializing_if = "Option::is_none", rename = "excludedResources")]
    pub excluded_resources: Option<Vec<String>>,
    #[serde(default, skip_serializing_if = "Option::is_none", rename = "includedNamespaces")]
    pub included_namespaces: Option<Vec<String>>,
    #[serde(default, skip_serializing_if = "Option::is_none", rename = "includedResources")]
    pub included_resources: Option<Vec<String>>,
    #[serde(default, skip_serializing_if = "Option::is_none", rename = "labelSelector")]
    pub label_selector: Option<ScheduleTemplateHooksResourcesLabelSelector>,
    pub name: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub post: Option<Vec<ScheduleTemplateHooksResourcesPost>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub pre: Option<Vec<ScheduleTemplateHooksResourcesPre>>,
}

#[derive(Serialize, Deserialize, Clone, Debug, Default)]
pub struct ScheduleTemplateHooksResourcesLabelSelector {
    #[serde(default, skip_serializing_if = "Option::is_none", rename = "matchExpressions")]
    pub match_expressions: Option<Vec<ScheduleTemplateHooksResourcesLabelSelectorMatchExpressions>>,
    #[serde(default, skip_serializing_if = "Option::is_none", rename = "matchLabels")]
    pub match_labels: Option<BTreeMap<String, String>>,
}

#[derive(Serialize, Deserialize, Clone, Debug, Default)]
pub struct ScheduleTemplateHooksResourcesLabelSelectorMatchExpressions {
    pub key: String,
    pub operator: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub values: Option<Vec<String>>,
}

#[derive(Serialize, Deserialize, Clone, Debug, Default)]
pub struct ScheduleTemplateHooksResourcesPost {
    pub exec: ScheduleTemplateHooksResourcesPostExec,
}

#[derive(Serialize, Deserialize, Clone, Debug, Default)]
pub struct ScheduleTemplateHooksResourcesPostExec {
    pub command: Vec<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub container: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none", rename = "onError")]
    pub on_error: Option<ScheduleTemplateHooksResourcesPostExecOnError>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub timeout: Option<String>,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub enum ScheduleTemplateHooksResourcesPostExecOnError {
    Continue,
    Fail,
}

#[derive(Serialize, Deserialize, Clone, Debug, Default)]
pub struct ScheduleTemplateHooksResourcesPre {
    pub exec: ScheduleTemplateHooksResourcesPreExec,
}

#[derive(Serialize, Deserialize, Clone, Debug, Default)]
pub struct ScheduleTemplateHooksResourcesPreExec {
    pub command: Vec<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub container: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none", rename = "onError")]
    pub on_error: Option<ScheduleTemplateHooksResourcesPreExecOnError>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub timeout: Option<String>,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub enum ScheduleTemplateHooksResourcesPreExecOnError {
    Continue,
    Fail,
}

#[derive(Serialize, Deserialize, Clone, Debug, Default)]
pub struct ScheduleTemplateLabelSelector {
    #[serde(default, skip_serializing_if = "Option::is_none", rename = "matchExpressions")]
    pub match_expressions: Option<Vec<ScheduleTemplateLabelSelectorMatchExpressions>>,
    #[serde(default, skip_serializing_if = "Option::is_none", rename = "matchLabels")]
    pub match_labels: Option<BTreeMap<String, String>>,
}

#[derive(Serialize, Deserialize, Clone, Debug, Default)]
pub struct ScheduleTemplateLabelSelectorMatchExpressions {
    pub key: String,
    pub operator: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub values: Option<Vec<String>>,
}

#[derive(Serialize, Deserialize, Clone, Debug, Default)]
pub struct ScheduleTemplateMetadata {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub labels: Option<BTreeMap<String, String>>,
}

#[derive(Serialize, Deserialize, Clone, Debug, Default)]
pub struct ScheduleTemplateOrLabelSelectors {
    #[serde(default, skip_serializing_if = "Option::is_none", rename = "matchExpressions")]
    pub match_expressions: Option<Vec<ScheduleTemplateOrLabelSelectorsMatchExpressions>>,
    #[serde(default, skip_serializing_if = "Option::is_none", rename = "matchLabels")]
    pub match_labels: Option<BTreeMap<String, String>>,
}

#[derive(Serialize, Deserialize, Clone, Debug, Default)]
pub struct ScheduleTemplateOrLabelSelectorsMatchExpressions {
    pub key: String,
    pub operator: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub values: Option<Vec<String>>,
}

#[derive(Serialize, Deserialize, Clone, Debug, Default)]
pub struct ScheduleTemplateResourcePolicy {
    #[serde(default, skip_serializing_if = "Option::is_none", rename = "apiGroup")]
    pub api_group: Option<String>,
    pub kind: String,
    pub name: String,
}

#[derive(Serialize, Deserialize, Clone, Debug, Default)]
pub struct ScheduleTemplateUploaderConfig {
    #[serde(default, skip_serializing_if = "Option::is_none", rename = "parallelFilesUpload")]
    pub parallel_files_upload: Option<i64>,
}

#[derive(Serialize, Deserialize, Clone, Debug, Default)]
pub struct ScheduleStatus {
    #[serde(default, skip_serializing_if = "Option::is_none", rename = "lastBackup")]
    pub last_backup: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none", rename = "lastSkipped")]
    pub last_skipped: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub phase: Option<ScheduleStatusPhase>,
    #[serde(default, skip_serializing_if = "Option::is_none", rename = "validationErrors")]
    pub validation_errors: Option<Vec<String>>,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub enum ScheduleStatusPhase {
    New,
    Enabled,
    FailedValidation,
}

