apiVersion: v1
kind: Secret
metadata:
  name: miniflux-postgres
  namespace: miniflux
stringData:
  username:
    sops: postgres.app_user.username
  password:
    sops: postgres.app_user.password
---
apiVersion: v1
kind: Secret
metadata:
  name: miniflux-admin
  namespace: miniflux
stringData:
  username:
    sops: miniflux.admin.username
  password:
    sops: miniflux.admin.password
