name  := "main-db"
default_flags := "-namespace main-db -force-conflicts"

takeoff extra_flags="":
	cargo build --target=wasm32-wasip1 --release
	yoke takeoff {{default_flags}} {{extra_flags}} {{name}} target/wasm32-wasip1/release/cnpg-database.wasm

debug extra_flags="":
	cargo build --target=wasm32-wasip1
	yoke takeoff -stdout {{default_flags}} {{extra_flags}} {{name}} target/wasm32-wasip1/debug/cnpg-database.wasm

diff extra_flags="":
	cargo build --target=wasm32-wasip1
	yoke takeoff -diff-only {{default_flags}} {{extra_flags}} {{name}} target/wasm32-wasip1/debug/cnpg-database.wasm

takeoff-restore extra_flags="":
	cargo build --target=wasm32-wasip1
	yoke takeoff {{default_flags}} {{extra_flags}} {{name}}-restore target/wasm32-wasip1/debug/cnpg-database.wasm -- --restore

debug-restore extra_flags="":
	cargo build --target=wasm32-wasip1
	yoke takeoff -stdout {{default_flags}} {{extra_flags}} {{name}}-restore target/wasm32-wasip1/debug/cnpg-database.wasm -- --restore

diff-restore extra_flags="":
	cargo build --target=wasm32-wasip1
	yoke takeoff -diff-only {{default_flags}} {{extra_flags}} {{name}}-restore target/wasm32-wasip1/debug/cnpg-database.wasm -- --restore
