apiVersion: v1
kind: Secret
metadata:
  name: wallabag-postgres
  namespace: wallabag
stringData:
  host: "main-db-rw.main-db"
  port: "5432"
  user:
    sops: postgres.app_user.username
  password:
    sops: postgres.app_user.password
