#!/usr/bin/env bash
kubectl create secret docker-registry \
    registry-creds -n "${1}" \
    --docker-server="registry.bgottlob.com" \
    --docker-username="${REGISTRY_USERNAME}" \
    --docker-password="${REGISTRY_PASSWORD}" \
    --docker-email="${REGISTRY_EMAIL}"
