name  := "csi-driver-linode"
default_flags := "-namespace kube-system -force-conflicts"

takeoff extra_flags="":
	cargo build --target=wasm32-wasip1 --release
	yoke takeoff {{default_flags}} {{extra_flags}} {{name}} target/wasm32-wasip1/release/{{name}}.wasm

debug extra_flags="":
	cargo build --target=wasm32-wasip1
	yoke takeoff -stdout {{default_flags}} {{extra_flags}} {{name}} target/wasm32-wasip1/debug/{{name}}.wasm

diff extra_flags="":
	cargo build --target=wasm32-wasip1
	yoke takeoff -diff-only {{default_flags}} {{extra_flags}} {{name}} target/wasm32-wasip1/debug/{{name}}.wasm
