---
apiVersion: v1
kind: Secret
metadata:
  name: miniflux-postgres
  namespace: miniflux
type: Opaque
stringData:
  database_url: "postgres://postgres:${POSTGRES_SUPER_USER_PASSWORD}@mypostgres.postgres/miniflux?sslmode=disable"
---
apiVersion: v1
kind: Secret
metadata:
  name: miniflux-admin
  namespace: miniflux
type: Opaque
stringData:
  username: "${MINIFLUX_ADMIN_USERNAME}"
  password: "${MINIFLUX_ADMIN_PASSWORD}"
