name          := "victoria-metrics-operator"
wasm_name     := name
deployment_dir := source_directory()
default_flags := "-namespace victoria-metrics-operator -create-namespace"

import '../shared_yoke.just'
