apiVersion: v1
kind: Secret
metadata:
  name: registry-s3-secret
  namespace: registry
stringData:
  accesskey:
    sops: registry.bucket.access_key_id
  secretkey:
    sops: registry.bucket.secret_key
---
apiVersion: v1
kind: Secret
metadata:
  name: registry-htpasswd-secret
  namespace: registry
stringData:
  htpasswd:
    sops: registry.auth.htpasswd
