name          := "main-db"
wasm_name     := "cnpg-database"
default_flags := "-namespace main-db -force-conflicts"

# Build and deploy to the cluster
takeoff extra_flags="":
	cargo build --target=wasm32-wasip1 --release
	yoke takeoff {{default_flags}} {{extra_flags}} {{name}} target/wasm32-wasip1/release/{{wasm_name}}.wasm

# Build and print rendered manifests to stdout without deploying
debug extra_flags="":
	cargo build --target=wasm32-wasip1
	yoke takeoff -stdout {{default_flags}} {{extra_flags}} {{name}} target/wasm32-wasip1/debug/{{wasm_name}}.wasm

# Build and show a diff of changes without deploying
diff extra_flags="":
	cargo build --target=wasm32-wasip1
	yoke takeoff -diff-only {{default_flags}} {{extra_flags}} {{name}} target/wasm32-wasip1/debug/{{wasm_name}}.wasm

# Build and deploy the restore cluster to the cluster
takeoff-restore extra_flags="":
	cargo build --target=wasm32-wasip1
	yoke takeoff {{default_flags}} {{extra_flags}} {{name}}-restore target/wasm32-wasip1/debug/{{wasm_name}}.wasm -- --restore

# Build and print rendered restore cluster manifests to stdout without deploying
debug-restore extra_flags="":
	cargo build --target=wasm32-wasip1
	yoke takeoff -stdout {{default_flags}} {{extra_flags}} {{name}}-restore target/wasm32-wasip1/debug/{{wasm_name}}.wasm -- --restore

# Build and show a diff of restore cluster changes without deploying
diff-restore extra_flags="":
	cargo build --target=wasm32-wasip1
	yoke takeoff -diff-only {{default_flags}} {{extra_flags}} {{name}}-restore target/wasm32-wasip1/debug/{{wasm_name}}.wasm -- --restore
