name := "{{ project-name }}"
default_flags := "-namespace {{ namespace }} -create-namespace"

takeoff extra_flags="":
	cargo build --target=wasm32-wasip1 --release
	{% raw %}yoke takeoff {{default_flags}} {{extra_flags}} {{name}} target/wasm32-wasip1/release/{{name}}.wasm{% endraw %}

debug extra_flags="":
	cargo build --target=wasm32-wasip1
	{% raw %}yoke takeoff -stdout {{default_flags}} {{extra_flags}} {{name}} target/wasm32-wasip1/debug/{{name}}.wasm{% endraw %}

diff extra_flags="":
	cargo build --target=wasm32-wasip1
	{% raw %}yoke takeoff -diff-only {{default_flags}} {{extra_flags}} {{name}} target/wasm32-wasip1/debug/{{name}}.wasm{% endraw %}
